#!/bin/bash
YEAR=2022
DAY=$1
PART=$2
MYDIR="$HOME/code/AdventOfCode"
USE_CODE=go
MYEDITOR=goland
if [ -z "$DAY" ]; then
    DAY=$(TZ=America/New_York date +%d)
fi
if [ -z "$PART" ]; then
    PART=1
fi
# Get aocdl from https://github.com/GreenLightning/advent-of-code-downloader
export AOC_SESSION=`cat ~/.aocdlconfig|jq -r '.["session-cookie"]'`
if [ ! -e utils/aoc ]; then
    cd utils
    go build -o aoc ./cmd/aoc/main.go
    cd ..
fi
./utils/aoc download -y $YEAR -d $DAY -p $PART
if [ $DAY -lt 10 ];then
    DAY=`printf "%02d" $DAY`
fi
cd "$MYDIR/$YEAR/$DAY" || exit 1
if [ "$USE_CODE" == "py" ]; then
    if [ ! -e part1.py ]; then
        cp -R ../template/*.py ./
    fi
elif [ "$USE_CODE" == "go" ]; then
    if [ ! -e part1.go ]; then
        go mod init "github.com/lazyguru/AdventOfCode/$YEAR/$DAY"
        cp -R ../template/*.go ./
    fi
fi
cp -R ../template/.gitignore ./
if [ "$MYEDITOR" == "nvim" ]; then
    tmux new -d -s "aoc$YEAR$DAY" -x "$(tput cols)" -y "$(tput lines)" "nvim input.txt"
    tmux split-window -t "aoc$YEAR$DAY" -h -p 80
    tmux split-window -t "aoc$YEAR$DAY" -bp 70 nvim -p puzzle.txt part$PART.$USE_CODE
    tmux attach -t "aoc$YEAR$DAY"
else
    $MYEDITOR .
fi
